name: MacZoomIt
options:
  bundleIdPrefix: com.maczoomit
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  MacZoomIt:
    type: application
    platform: macOS
    sources:
      - MacZoomIt
    info:
      path: MacZoomIt/Info.plist
      properties:
        LSUIElement: true
        CFBundleName: MacZoomIt
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        NSHumanReadableCopyright: "Copyright 2024. All rights reserved."
    entitlements:
      path: MacZoomIt/MacZoomIt.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.maczoomit.MacZoomIt
      INFOPLIST_FILE: MacZoomIt/Info.plist
      CODE_SIGN_ENTITLEMENTS: MacZoomIt/MacZoomIt.entitlements
      ENABLE_HARDENED_RUNTIME: NO
